/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ColecoesRouteImport } from './routes/colecoes'
import { Route as PokemonDexRouteImport } from './routes/pokemon.$dex'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecoesRoute = ColecoesRouteImport.update({
  id: '/colecoes',
  path: '/colecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PokemonDexRoute = PokemonDexRouteImport.update({
  id: '/pokemon/$dex',
  path: '/pokemon/$dex',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colecoes': typeof ColecoesRoute
  '/pokemon/$dex': typeof PokemonDexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colecoes': typeof ColecoesRoute
  '/pokemon/$dex': typeof PokemonDexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colecoes': typeof ColecoesRoute
  '/pokemon/$dex': typeof PokemonDexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/colecoes' | '/pokemon/$dex'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/colecoes' | '/pokemon/$dex'
  id: '__root__' | '/' | '/auth' | '/colecoes' | '/pokemon/$dex'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ColecoesRoute: typeof ColecoesRoute
  PokemonDexRoute: typeof PokemonDexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecoes': {
      id: '/colecoes'
      path: '/colecoes'
      fullPath: '/colecoes'
      preLoaderRoute: typeof ColecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokemon/$dex': {
      id: '/pokemon/$dex'
      path: '/pokemon/$dex'
      fullPath: '/pokemon/$dex'
      preLoaderRoute: typeof PokemonDexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ColecoesRoute: ColecoesRoute,
  PokemonDexRoute: PokemonDexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
