/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ColecoesRouteImport } from './routes/colecoes'
import { Route as ProcuradasRouteImport } from './routes/procuradas'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as PokemonDexRouteImport } from './routes/pokemon.$dex'
import { Route as BindersRouteImport } from './routes/binders'
import { Route as BinderSlugRouteImport } from './routes/binder.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecoesRoute = ColecoesRouteImport.update({
  id: '/colecoes',
  path: '/colecoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcuradasRoute = ProcuradasRouteImport.update({
  id: '/procuradas',
  path: '/procuradas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PokemonDexRoute = PokemonDexRouteImport.update({
  id: '/pokemon/$dex',
  path: '/pokemon/$dex',
  getParentRoute: () => rootRouteImport,
} as any)
const BindersRoute = BindersRouteImport.update({
  id: '/binders',
  path: '/binders',
  getParentRoute: () => rootRouteImport,
} as any)
const BinderSlugRoute = BinderSlugRouteImport.update({
  id: '/binder/$slug',
  path: '/binder/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colecoes': typeof ColecoesRoute
  '/procuradas': typeof ProcuradasRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/pokemon/$dex': typeof PokemonDexRoute
  '/binders': typeof BindersRoute
  '/binder/$slug': typeof BinderSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colecoes': typeof ColecoesRoute
  '/procuradas': typeof ProcuradasRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/pokemon/$dex': typeof PokemonDexRoute
  '/binders': typeof BindersRoute
  '/binder/$slug': typeof BinderSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/colecoes': typeof ColecoesRoute
  '/procuradas': typeof ProcuradasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/pokemon/$dex': typeof PokemonDexRoute
  '/binders': typeof BindersRoute
  '/binder/$slug': typeof BinderSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/colecoes' | '/procuradas' | '/admin' | '/pokemon/$dex' | '/binders' | '/binder/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/colecoes' | '/procuradas' | '/admin' | '/pokemon/$dex' | '/binders' | '/binder/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/colecoes'
    | '/procuradas'
    | '/_authenticated/admin'
    | '/pokemon/$dex'
    | '/binders'
    | '/binder/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ColecoesRoute: typeof ColecoesRoute
  ProcuradasRoute: typeof ProcuradasRoute
  PokemonDexRoute: typeof PokemonDexRoute
  BindersRoute: typeof BindersRoute
  BinderSlugRoute: typeof BinderSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecoes': {
      id: '/colecoes'
      path: '/colecoes'
      fullPath: '/colecoes'
      preLoaderRoute: typeof ColecoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procuradas': {
      id: '/procuradas'
      path: '/procuradas'
      fullPath: '/procuradas'
      preLoaderRoute: typeof ProcuradasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/pokemon/$dex': {
      id: '/pokemon/$dex'
      path: '/pokemon/$dex'
      fullPath: '/pokemon/$dex'
      preLoaderRoute: typeof PokemonDexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binders': {
      id: '/binders'
      path: '/binders'
      fullPath: '/binders'
      preLoaderRoute: typeof BindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/binder/$slug': {
      id: '/binder/$slug'
      path: '/binder/$slug'
      fullPath: '/binder/$slug'
      preLoaderRoute: typeof BinderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ColecoesRoute: ColecoesRoute,
  ProcuradasRoute: ProcuradasRoute,
  PokemonDexRoute: PokemonDexRoute,
  BindersRoute: BindersRoute,
  BinderSlugRoute: BinderSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
